language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dockerreactapp/reactwebapp -f Dockerfile.dev .

scritp:
    - docker run -e CI=true dockerreactapp/reactwebapp npm run test -- --coverage

